{
  "formatVersion": "1.1",
  "component": {
    "group": "com.otcengineering.elausasdk",
    "module": "ElausaSDK",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.runtime.mcumgr",
          "module": "mcumgr-ble",
          "version": {
            "requires": "0.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "ElausaSDK-1.0.0.aar",
          "url": "ElausaSDK-1.0.0.aar",
          "size": 146301,
          "sha512": "a73b1bbbeaf105f1e03eae138448ae7f15be60188f6e8903e1635baffc42c90d67df8ab81cc91da975aa211711ccbfc665bcc2c35d686863c3a0f5776e3620d2",
          "sha256": "0f732803aca73157a1796d9c8d48e5fccd41f89543856faf023673b0960832d2",
          "sha1": "501846876ae8c972783aed20d4578276887b2ac5",
          "md5": "3b541877204205220ca827d0158c8d10"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.runtime.mcumgr",
          "module": "mcumgr-ble",
          "version": {
            "requires": "0.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.vmadalin",
          "module": "easypermissions-ktx",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.github.PhilJay",
          "module": "MPAndroidChart",
          "version": {
            "requires": "v3.1.0"
          }
        },
        {
          "group": "no.nordicsemi.android.support.v18",
          "module": "scanner",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.jakewharton.threetenabp",
          "module": "threetenabp",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "uk.me.berndporr",
          "module": "iirj",
          "version": {
            "requires": "1.4"
          }
        }
      ],
      "files": [
        {
          "name": "ElausaSDK-1.0.0.aar",
          "url": "ElausaSDK-1.0.0.aar",
          "size": 146301,
          "sha512": "a73b1bbbeaf105f1e03eae138448ae7f15be60188f6e8903e1635baffc42c90d67df8ab81cc91da975aa211711ccbfc665bcc2c35d686863c3a0f5776e3620d2",
          "sha256": "0f732803aca73157a1796d9c8d48e5fccd41f89543856faf023673b0960832d2",
          "sha1": "501846876ae8c972783aed20d4578276887b2ac5",
          "md5": "3b541877204205220ca827d0158c8d10"
        }
      ]
    }
  ]
}
